### ISSUE TITLE
Investigate the effect of LED indication of PIR motion on light sensing

### ISSUE THREAD

**Issue by EarthLord** [Appiko/nrf5x-firmware#5]
In the first SENSE_FEEDBACK_TIMEOUT_MS a red pulse indication is given to the user on detecting motion. Will this have any effect if the light sensing also happens at the same time?

**Comment by tejas-tj** [comment]
Yes, LED blinking will affect the light sensing. It'll cause false negatives for light  conditions if device is set for night_time with low light threshold. Here are some readings from a experiment. These readings were taken after confirming that almost no light can enter into the setup.
These are the readings without led blinking
`[19:10:41.249683 0.000001] Light Intensity : 57`
`[19:10:46.248563 4.998882] Light Intensity : 29`
`[19:10:51.247485 4.998922] Light Intensity : 15`
`[19:10:56.246236 4.998752] Light Intensity : 52`
`[19:11:01.245143 4.998906] Light Intensity : 47`
`[19:11:06.244020 4.998866] Light Intensity : 35`
`[19:11:11.242976 4.998967] Light Intensity : 24`
`[19:11:16.241933 4.998957] Light Intensity : 50`

And, these are the readings with led blinking
`[18:54:29.616827 0.000001] Light Intensity : 1110`
`[18:54:34.617241 5.000417] Light Intensity : 1045`
`[18:54:39.617725 5.000482] Light Intensity : 1107`
`[18:54:44.618186 5.000464] Light Intensity : 1107`
`[18:54:49.618533 5.000345] Light Intensity : 1083`
`[18:54:54.618988 5.000457] Light Intensity : 1117`
`[18:54:59.619241 5.000253] Light Intensity : 985 `
`[18:55:04.619786 5.000545] Light Intensity : 1156 `
`[18:55:09.620106 5.000319] Light Intensity : 970  `
`[18:55:14.620469 5.000363] Light Intensity : 1099`
`[18:55:19.620741 5.000272] Light Intensity : 1100`
`[18:55:24.621127 5.000386] Light Intensity : 1101`
`[18:55:29.621394 5.000268] Light Intensity : 1090`
`[18:55:34.621715 5.000321] Light Intensity : 1084`
`[18:55:39.621980 5.000265] Light Intensity : 1106`
`[18:55:44.622259 5.000279] Light Intensity : 991 `
`[18:55:49.622507 5.000248] Light Intensity : 1112`
`[18:55:54.622656 5.000148] Light Intensity : 1096`
`[18:55:59.622857 5.000202] Light Intensity : 1146`
