### ISSUE TITLE
HTTP response data for the application not supported

### ISSUE THREAD

**Issue by EarthLord** [Appiko/nrf5x-firmware#7]
Although the struct for 'sim800_http_req_t' has a request type for GET, it is not supported to get the response data from either GET or POST. We can make an implementation where the buffer is in SIM800 module or the main application. Where would the location of the buffer be better?

https://github.com/Appiko/nrf5x-firmware/blob/7855deec9e95a0f5b432030f7586d122a47c79a7/codebase/AT_lib/sim800_oper.h#L116

**Comment by tejas-tj** [comment]
Not yet. That'll be the part of the next revision of this library.
