### ISSUE TITLE
Use of the return value?

### ISSUE THREAD

**Issue by EarthLord** [Appiko/nrf5x-firmware#8]
Connection ID is for?

https://github.com/Appiko/nrf5x-firmware/blob/7855deec9e95a0f5b432030f7586d122a47c79a7/codebase/AT_lib/sim800_oper.h#L164

**Comment by tejas-tj** [comment]
That'll be useful when we decide to connect to multiple servers. I'll add TODO to it

**Comment by EarthLord** [comment]
After adding TODO, we can make it void return for now?
